import { expect, test } from "bun:test";
import { buildSafeSubtitleTracks } from "../src/components/subtitle-track-utils";

Object.assign(globalThis, { window: { location: { origin: "https://typetype.test" } } });

test("uses caption variants instead of numeric duplicate language labels", () => {
  const tracks = buildSafeSubtitleTracks([
    {
      url: "https://www.youtube.com/api/timedtext?lang=en&name=CC1",
      mimeType: "text/vtt",
      languageTag: "en",
      displayLanguageName: "English",
      isAutoGenerated: false,
    },
    {
      url: "https://www.youtube.com/api/timedtext?lang=en&name=DTVCC1",
      mimeType: "text/vtt",
      languageTag: "en",
      displayLanguageName: "English",
      isAutoGenerated: false,
    },
  ]);

  expect(tracks.map((track) => track.label)).toEqual(["English (CC1)", "English (DTVCC1)"]);
  expect(tracks.every((track) => new URL(track.src).searchParams.get("fmt") === "vtt")).toBe(true);
  expect(tracks.every((track) => new URL(track.src).hostname === "www.youtube.com")).toBe(true);
});
