import { expect, test } from "bun:test";
import { buildSafeSubtitleTracks } from "../src/components/subtitle-track-utils";

Object.assign(globalThis, { window: { location: { origin: "https://typetype.test" } } });

test("uses caption variants instead of numeric duplicate language labels", () => {
  const tracks = buildSafeSubtitleTracks([
    {
      url: "https://www.youtube.com/api/timedtext?v=abcdefghijk&lang=en&name=CC1&expire=123&sig=secret",
      mimeType: "text/vtt",
      languageTag: "en",
      displayLanguageName: "English",
      isAutoGenerated: false,
    },
    {
      url: "https://www.youtube.com/api/timedtext?v=abcdefghijk&lang=en&name=DTVCC1&expire=456&sig=secret",
      mimeType: "text/vtt",
      languageTag: "en",
      displayLanguageName: "English",
      isAutoGenerated: false,
    },
  ]);

  expect(tracks.map((track) => track.label)).toEqual(["English (CC1)", "English (DTVCC1)"]);
  expect(tracks.every((track) => new URL(track.src).searchParams.get("fmt") === "vtt")).toBe(true);
  expect(tracks.every((track) => new URL(track.src).hostname === "www.youtube.com")).toBe(true);
  expect(tracks.every((track) => new URL(track.src).pathname === "/api/timedtext")).toBe(true);
  expect(tracks.every((track) => track.src.includes("sig=secret"))).toBe(true);
});

test("preserves generated and translated YouTube subtitle selection", () => {
  const [track] = buildSafeSubtitleTracks([
    {
      url: "https://m.youtube.com/api/timedtext?v=abcdefghijk&lang=en&kind=asr&tlang=fr",
      mimeType: "application/ttml+xml",
      languageTag: "fr",
      displayLanguageName: "French",
      isAutoGenerated: false,
    },
  ]);

  const src = new URL(track?.src ?? "");
  expect(src.hostname).toBe("m.youtube.com");
  expect(src.searchParams.get("fmt")).toBe("vtt");
  expect(src.searchParams.get("lang")).toBe("en");
  expect(src.searchParams.get("kind")).toBe("asr");
  expect(src.searchParams.get("tlang")).toBe("fr");
});

test("keeps non YouTube subtitle tracks on the generic proxy", () => {
  const [track] = buildSafeSubtitleTracks([
    {
      url: "https://subtitles.example.test/captions.ttml",
      mimeType: "application/ttml+xml",
      languageTag: "en",
      displayLanguageName: "English",
      isAutoGenerated: false,
    },
  ]);

  const src = new URL(track?.src ?? "");
  expect(src.pathname).toBe("/api/proxy");
  expect(src.searchParams.get("url")).toContain("fmt=vtt");
});
