/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PlaylistsRouteImport } from './routes/playlists'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ChannelRouteImport } from './routes/channel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaylistsIdRouteImport } from './routes/playlists_.$id'

const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsRoute = PlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelRoute = ChannelRouteImport.update({
  id: '/channel',
  path: '/channel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIdRoute = PlaylistsIdRouteImport.update({
  id: '/playlists_/$id',
  path: '/playlists/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channel': typeof ChannelRoute
  '/history': typeof HistoryRoute
  '/playlists': typeof PlaylistsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/trending': typeof TrendingRoute
  '/watch': typeof WatchRoute
  '/playlists/$id': typeof PlaylistsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channel': typeof ChannelRoute
  '/history': typeof HistoryRoute
  '/playlists': typeof PlaylistsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/trending': typeof TrendingRoute
  '/watch': typeof WatchRoute
  '/playlists/$id': typeof PlaylistsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/channel': typeof ChannelRoute
  '/history': typeof HistoryRoute
  '/playlists': typeof PlaylistsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/trending': typeof TrendingRoute
  '/watch': typeof WatchRoute
  '/playlists_/$id': typeof PlaylistsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/channel'
    | '/history'
    | '/playlists'
    | '/search'
    | '/settings'
    | '/subscriptions'
    | '/trending'
    | '/watch'
    | '/playlists/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/channel'
    | '/history'
    | '/playlists'
    | '/search'
    | '/settings'
    | '/subscriptions'
    | '/trending'
    | '/watch'
    | '/playlists/$id'
  id:
    | '__root__'
    | '/'
    | '/channel'
    | '/history'
    | '/playlists'
    | '/search'
    | '/settings'
    | '/subscriptions'
    | '/trending'
    | '/watch'
    | '/playlists_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelRoute: typeof ChannelRoute
  HistoryRoute: typeof HistoryRoute
  PlaylistsRoute: typeof PlaylistsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  TrendingRoute: typeof TrendingRoute
  WatchRoute: typeof WatchRoute
  PlaylistsIdRoute: typeof PlaylistsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel': {
      id: '/channel'
      path: '/channel'
      fullPath: '/channel'
      preLoaderRoute: typeof ChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists_/$id': {
      id: '/playlists_/$id'
      path: '/playlists/$id'
      fullPath: '/playlists/$id'
      preLoaderRoute: typeof PlaylistsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelRoute: ChannelRoute,
  HistoryRoute: HistoryRoute,
  PlaylistsRoute: PlaylistsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  TrendingRoute: TrendingRoute,
  WatchRoute: WatchRoute,
  PlaylistsIdRoute: PlaylistsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
