import type { VideoStream } from "../types/stream";

export type ShortsPlayerStageProps = {
  sectionClass: string;
  playerRef: React.RefObject<HTMLDivElement | null>;
  commentsOpen: boolean;
  active: VideoStream;
  current: VideoStream;
  stream: VideoStream | undefined;
  streamLoading: boolean;
  streamError: boolean;
  errorMessage: string;
  isMemberOnlyShort: boolean;
  youtubeSessionReturnTo?: string;
  hasPrev: boolean;
  hasNext: boolean;
  settingsReady: boolean;
  autoplay: boolean;
  initialVolume: number;
  initialMuted: boolean;
  defaultQuality?: string;
  defaultPlaybackSpeed: number;
  defaultAudioLanguage?: string;
  preferOriginalLanguage?: boolean;
  originalAudioTrackId?: string | null;
  preferredDefaultAudioTrackId?: string | null;
  originalAudioLocale?: string | null;
  defaultSubtitleLanguage?: string;
  subtitlesEnabled?: boolean;
  showComments: boolean;
  onOpenComments: () => void;
  onCloseComments: () => void;
  onRetry: () => void;
  onNext: () => void;
  onAutoNext: () => void;
  onPrev: () => void;
  onWheel: (event: React.WheelEvent) => void;
  onTouchStart: (clientY: number | null, target: EventTarget | null) => void;
  onTouchEnd: (clientY: number | null, target: EventTarget | null) => void;
  onVolumeChange: (volume: number, muted: boolean) => void;
};
