import type { MediaSrc } from "@vidstack/react";
import { MediaPlayer, MediaProvider, Track } from "@vidstack/react";
import { DefaultVideoLayout, defaultLayoutIcons } from "@vidstack/react/player/layouts/default";
import { toProxiedVttUrl } from "../lib/proxy";
import type { SubtitleItem } from "../types/api";
import { AudioTrackSelector } from "./audio-track-selector";
import { PlayerDefaults } from "./player-internals";
import { onProviderChange } from "./video-player-core";
import { VolumeRestorer } from "./volume-restorer";

type Props = {
  src: MediaSrc;
  title?: string;
  poster?: string;
  subtitles?: SubtitleItem[];
  initialVolume?: number;
  initialMuted?: boolean;
  settingsReady?: boolean;
  autoplay?: boolean;
  defaultAudioLanguage?: string;
  preferOriginalLanguage?: boolean;
  originalAudioLocale?: string | null;
  defaultSubtitleLanguage?: string;
  subtitlesEnabled?: boolean;
  onVolumeChange?: (volume: number, muted: boolean) => void;
  onError?: () => void;
  onEnded?: () => void;
};

export function ShortsVideoPlayer({
  src,
  title,
  poster,
  subtitles,
  initialVolume = 1,
  initialMuted = false,
  settingsReady = false,
  autoplay = true,
  defaultAudioLanguage,
  preferOriginalLanguage,
  originalAudioLocale,
  defaultSubtitleLanguage,
  subtitlesEnabled,
  onVolumeChange,
  onError,
  onEnded,
}: Props) {
  const srcKey = typeof src === "string" ? src : String(src.src);

  return (
    <div style={{ position: "absolute", inset: 0, backgroundColor: "black" }}>
      <MediaPlayer
        key={srcKey}
        src={src}
        title={title}
        poster={poster}
        viewType="video"
        streamType="on-demand"
        logLevel="warn"
        crossOrigin
        playsInline
        autoPlay={autoplay}
        storage={null}
        onProviderChange={onProviderChange}
        onError={() => onError?.()}
        onEnded={() => onEnded?.()}
        style={{
          position: "absolute",
          inset: 0,
          width: "100%",
          height: "100%",
          "--media-object-fit": "cover",
        }}
      >
        <MediaProvider
          style={{ position: "absolute", inset: 0, width: "100%", height: "100%" }}
          mediaProps={{
            style: {
              position: "absolute",
              inset: "0",
              width: "100%",
              height: "100%",
              objectFit: "cover",
            },
          }}
        >
          {subtitles?.map((s) => (
            <Track
              key={`${s.languageTag}-${s.isAutoGenerated}`}
              kind="subtitles"
              src={toProxiedVttUrl(s.url)}
              label={s.displayLanguageName}
              lang={s.languageTag}
              type="vtt"
            />
          ))}
        </MediaProvider>
        <DefaultVideoLayout
          icons={defaultLayoutIcons}
          translations={{ Captions: "Subtitles" }}
          smallLayoutWhen
          noModal
          menuContainer="body"
          menuGroup="bottom"
          slots={{
            settingsMenuItemsStart: <AudioTrackSelector />,
          }}
        />
        <PlayerDefaults
          defaultAudioLanguage={defaultAudioLanguage}
          preferOriginalLanguage={preferOriginalLanguage}
          originalAudioLocale={originalAudioLocale}
          defaultSubtitleLanguage={defaultSubtitleLanguage}
          subtitlesEnabled={subtitlesEnabled}
        />
        <VolumeRestorer
          initialVolume={initialVolume}
          initialMuted={initialMuted}
          settingsReady={settingsReady}
          autoplay={autoplay}
          onVolumeChange={onVolumeChange}
        />
      </MediaPlayer>
    </div>
  );
}
