import { toProxiedVttUrl } from "../lib/proxy";
import type { SubtitleItem } from "../types/api";

type SafeSubtitleTrack = {
  key: string;
  id: string;
  src: string;
  label: string;
  lang: string;
};

function normalizeText(value: unknown): string {
  return typeof value === "string" ? value.trim() : "";
}

function uniqueLabel(base: string, isAuto: boolean, used: Map<string, number>): string {
  const label = isAuto ? `${base} (auto)` : base;
  const seen = used.get(label) ?? 0;
  used.set(label, seen + 1);
  return seen > 0 ? `${label} (${seen + 1})` : label;
}

function subtitleVariant(url: string): string {
  try {
    const name = new URL(url).searchParams.get("name")?.trim();
    return name && /^[a-zA-Z0-9._-]{1,24}$/.test(name) ? name : "";
  } catch {
    return "";
  }
}

export function buildSafeSubtitleTracks(
  subtitles: SubtitleItem[] | undefined,
): SafeSubtitleTrack[] {
  if (!subtitles || subtitles.length === 0) return [];

  const tracks: SafeSubtitleTrack[] = [];
  const usedLabels = new Map<string, number>();

  for (let i = 0; i < subtitles.length; i++) {
    const item = subtitles[i];
    if (!item) continue;

    const rawUrl = normalizeText(item.url);
    if (!rawUrl) continue;

    let src = "";
    try {
      src = toProxiedVttUrl(rawUrl);
    } catch {
      continue;
    }

    const lang = normalizeText(item.languageTag).toLowerCase() || `und-${i}`;
    const languageLabel = normalizeText(item.displayLanguageName) || lang;
    const variant = subtitleVariant(rawUrl);
    const baseLabel = variant ? `${languageLabel} (${variant})` : languageLabel;
    const label = uniqueLabel(baseLabel, item.isAutoGenerated, usedLabels);

    tracks.push({ key: `${lang}-${rawUrl}-${i}`, id: `sub-${lang}-${i}`, src, label, lang });
  }

  return tracks;
}
