export type VideoStreamItem = {
  url: string;
  format: string;
  resolution: string;
  bitrate: number | null;
  codec: string | null;
  mimeType: string;
  isVideoOnly: boolean;
  itag: number;
  width: number;
  height: number;
  fps: number;
  contentLength: number;
  initStart: number;
  initEnd: number;
  indexStart: number;
  indexEnd: number;
};

export type AudioStreamItem = {
  url: string;
  format: string;
  bitrate: number | null;
  codec: string | null;
  mimeType: string;
  quality: string | null;
  audioTrackId: string | null;
  audioTrackName: string | null;
  audioLocale: string | null;
  itag: number;
  contentLength: number;
  initStart: number;
  initEnd: number;
  indexStart: number;
  indexEnd: number;
};

export type SponsorBlockSegmentItem = {
  startTime: number;
  endTime: number;
  category: string;
  action: string;
};

export type SubtitleItem = {
  url: string;
  mimeType: string;
  languageTag: string;
  displayLanguageName: string;
  isAutoGenerated: boolean;
};

export type PreviewFrameItem = {
  urls: string[];
  frameWidth: number;
  frameHeight: number;
  totalCount: number;
  durationPerFrame: number;
  framesPerPageX: number;
  framesPerPageY: number;
};

export type StreamSegmentItem = {
  title: string;
  startTimeSeconds: number;
  channelName: string | null;
  url: string | null;
  previewUrl: string | null;
};

export type VideoItem = {
  id: string;
  title: string;
  url: string;
  thumbnailUrl: string;
  uploaderName: string;
  uploaderUrl: string;
  uploaderAvatarUrl: string;
  uploaderVerified: boolean;
  duration: number;
  viewCount: number;
  uploadDate: string;
  streamType: string;
  isShortFormContent: boolean;
  shortDescription: string | null;
};

export type StreamResponse = {
  id: string;
  title: string;
  uploaderName: string;
  uploaderUrl: string;
  uploaderAvatarUrl: string;
  thumbnailUrl: string;
  description: string;
  duration: number;
  viewCount: number;
  likeCount: number;
  dislikeCount: number;
  uploadDate: string;
  uploaded: number;
  uploaderSubscriberCount: number;
  uploaderVerified: boolean;
  category: string;
  license: string;
  visibility: string;
  tags: string[];
  streamType: string;
  isShortFormContent: boolean;
  requiresMembership: boolean;
  startPosition: number;
  streamSegments: StreamSegmentItem[];
  hlsUrl: string;
  dashMpdUrl: string;
  videoStreams: VideoStreamItem[];
  audioStreams: AudioStreamItem[];
  videoOnlyStreams: VideoStreamItem[];
  sponsorBlockSegments: SponsorBlockSegmentItem[];
  subtitles: SubtitleItem[];
  previewFrames: PreviewFrameItem[];
  relatedStreams: VideoItem[];
};

export type SearchPageResponse = {
  items: VideoItem[];
  nextpage: string | null;
  searchSuggestion: string | null;
  isCorrectedSearch: boolean;
};

export type CommentItem = {
  id: string;
  text: string;
  author: string;
  authorUrl: string;
  authorAvatarUrl: string;
  likeCount: number;
  textualLikeCount: string;
  publishedTime: string;
  isHeartedByUploader: boolean;
  isPinned: boolean;
  uploaderVerified: boolean;
  replyCount: number;
  repliesPage: string | null;
};

export type CommentsPageResponse = {
  comments: CommentItem[];
  nextpage: string | null;
  commentsDisabled: boolean;
};

export type ChannelResponse = {
  name: string;
  description: string;
  avatarUrl: string;
  bannerUrl: string;
  subscriberCount: number;
  isVerified: boolean;
  videos: VideoItem[];
  nextpage: string | null;
};
