export type VideoStreamItem = {
  url: string;
  format: string;
  resolution: string;
  bitrate: number | null;
  codec: string | null;
  mimeType: string;
  isVideoOnly: boolean;
  itag: number;
  width: number;
  height: number;
  fps: number;
  contentLength: number;
  initStart: number;
  initEnd: number;
  indexStart: number;
  indexEnd: number;
};

export type AudioStreamItem = {
  url: string;
  format: string;
  bitrate: number | null;
  codec: string | null;
  mimeType: string;
  quality: string | null;
  audioTrackId: string | null;
  audioTrackName: string | null;
  audioLocale: string | null;
  itag: number;
  contentLength: number;
  initStart: number;
  initEnd: number;
  indexStart: number;
  indexEnd: number;
};

export type SponsorBlockSegmentItem = {
  startTime: number;
  endTime: number;
  category: string;
  action: string;
};

export type SubtitleItem = {
  url: string;
  mimeType: string;
  languageTag: string;
  displayLanguageName: string;
  isAutoGenerated: boolean;
};

export type PreviewFrameItem = {
  urls: string[];
  frameWidth: number;
  frameHeight: number;
  totalCount: number;
  durationPerFrame: number;
  framesPerPageX: number;
  framesPerPageY: number;
};

export type StreamSegmentItem = {
  title: string;
  startTimeSeconds: number;
  channelName: string | null;
  url: string | null;
  previewUrl: string | null;
};
