export type Language = {
  code: string;
  label: string;
};

export const LANGUAGES: Language[] = [
  { code: "af", label: "Afrikaans" },
  { code: "sq", label: "Albanian — Shqip" },
  { code: "am", label: "Amharic — አማርኛ" },
  { code: "ar", label: "Arabic — العربية" },
  { code: "hy", label: "Armenian — Հայերեն" },
  { code: "az", label: "Azerbaijani — Azərbaycan" },
  { code: "eu", label: "Basque — Euskara" },
  { code: "be", label: "Belarusian — Беларуская" },
  { code: "bn", label: "Bengali — বাংলা" },
  { code: "bs", label: "Bosnian — Bosanski" },
  { code: "bg", label: "Bulgarian — Български" },
  { code: "ca", label: "Catalan — Català" },
  { code: "ceb", label: "Cebuano" },
  { code: "zh", label: "Chinese (Simplified) — 中文" },
  { code: "zh-TW", label: "Chinese (Traditional) — 繁體中文" },
  { code: "co", label: "Corsican — Corsu" },
  { code: "hr", label: "Croatian — Hrvatski" },
  { code: "cs", label: "Czech — Čeština" },
  { code: "da", label: "Danish — Dansk" },
  { code: "nl", label: "Dutch — Nederlands" },
  { code: "en", label: "English" },
  { code: "eo", label: "Esperanto" },
  { code: "et", label: "Estonian — Eesti" },
  { code: "fi", label: "Finnish — Suomi" },
  { code: "fr", label: "French — Français" },
  { code: "fy", label: "Frisian — Frysk" },
  { code: "gl", label: "Galician — Galego" },
  { code: "ka", label: "Georgian — ქართული" },
  { code: "de", label: "German — Deutsch" },
  { code: "el", label: "Greek — Ελληνικά" },
  { code: "gu", label: "Gujarati — ગુજરાતી" },
  { code: "ht", label: "Haitian Creole" },
  { code: "ha", label: "Hausa" },
  { code: "haw", label: "Hawaiian — ʻŌlelo Hawaiʻi" },
  { code: "he", label: "Hebrew — עברית" },
  { code: "hi", label: "Hindi — हिन्दी" },
  { code: "hmn", label: "Hmong" },
  { code: "hu", label: "Hungarian — Magyar" },
  { code: "is", label: "Icelandic — Íslenska" },
  { code: "ig", label: "Igbo" },
  { code: "id", label: "Indonesian — Bahasa Indonesia" },
  { code: "ga", label: "Irish — Gaeilge" },
  { code: "it", label: "Italian — Italiano" },
  { code: "ja", label: "Japanese — 日本語" },
  { code: "jv", label: "Javanese — Basa Jawa" },
  { code: "kn", label: "Kannada — ಕನ್ನಡ" },
  { code: "kk", label: "Kazakh — Қазақ" },
  { code: "km", label: "Khmer — ភាសាខ្មែរ" },
  { code: "rw", label: "Kinyarwanda" },
  { code: "ko", label: "Korean — 한국어" },
  { code: "ku", label: "Kurdish — Kurdî" },
  { code: "ky", label: "Kyrgyz — Кыргызча" },
  { code: "lo", label: "Lao — ລາວ" },
  { code: "la", label: "Latin" },
  { code: "lv", label: "Latvian — Latviešu" },
  { code: "lt", label: "Lithuanian — Lietuvių" },
  { code: "lb", label: "Luxembourgish — Lëtzebuergesch" },
  { code: "mk", label: "Macedonian — Македонски" },
  { code: "mg", label: "Malagasy" },
  { code: "ms", label: "Malay — Bahasa Melayu" },
  { code: "ml", label: "Malayalam — മലയാളം" },
  { code: "mt", label: "Maltese — Malti" },
  { code: "mi", label: "Maori — Te Reo Māori" },
  { code: "mr", label: "Marathi — मराठी" },
  { code: "mn", label: "Mongolian — Монгол" },
  { code: "my", label: "Myanmar (Burmese) — မြန်မာ" },
  { code: "ne", label: "Nepali — नेपाली" },
  { code: "no", label: "Norwegian — Norsk" },
  { code: "ny", label: "Nyanja (Chichewa)" },
  { code: "or", label: "Odia (Oriya) — ଓଡ଼ିଆ" },
  { code: "ps", label: "Pashto — پښتو" },
  { code: "fa", label: "Persian — فارسی" },
  { code: "pl", label: "Polish — Polski" },
  { code: "pt", label: "Portuguese — Português" },
  { code: "pa", label: "Punjabi — ਪੰਜਾਬੀ" },
  { code: "ro", label: "Romanian — Română" },
  { code: "ru", label: "Russian — Русский" },
  { code: "sm", label: "Samoan — Gagana Samoa" },
  { code: "gd", label: "Scots Gaelic — Gàidhlig" },
  { code: "sr", label: "Serbian — Српски" },
  { code: "st", label: "Sesotho" },
  { code: "sn", label: "Shona — ChiShona" },
  { code: "sd", label: "Sindhi — سنڌي" },
  { code: "si", label: "Sinhala — සිංහල" },
  { code: "sk", label: "Slovak — Slovenčina" },
  { code: "sl", label: "Slovenian — Slovenščina" },
  { code: "so", label: "Somali — Soomaali" },
  { code: "es", label: "Spanish — Español" },
  { code: "su", label: "Sundanese — Basa Sunda" },
  { code: "sw", label: "Swahili — Kiswahili" },
  { code: "sv", label: "Swedish — Svenska" },
  { code: "tl", label: "Tagalog (Filipino)" },
  { code: "tg", label: "Tajik — Тоҷикӣ" },
  { code: "ta", label: "Tamil — தமிழ்" },
  { code: "tt", label: "Tatar — Татарча" },
  { code: "te", label: "Telugu — తెలుగు" },
  { code: "th", label: "Thai — ภาษาไทย" },
  { code: "tr", label: "Turkish — Türkçe" },
  { code: "tk", label: "Turkmen — Türkmen" },
  { code: "uk", label: "Ukrainian — Українська" },
  { code: "ur", label: "Urdu — اردو" },
  { code: "ug", label: "Uyghur — ئۇيغۇرچە" },
  { code: "uz", label: "Uzbek — O'zbek" },
  { code: "vi", label: "Vietnamese — Tiếng Việt" },
  { code: "cy", label: "Welsh — Cymraeg" },
  { code: "xh", label: "Xhosa — isiXhosa" },
  { code: "yi", label: "Yiddish — ייִדיש" },
  { code: "yo", label: "Yoruba" },
  { code: "zu", label: "Zulu — isiZulu" },
];
