export type Language = {
  code: string;
  label: string;
  flag?: string;
};

export const LANGUAGES: Language[] = [
  { code: "af", label: "Afrikaans", flag: "ZA" },
  { code: "sq", label: "Albanian — Shqip", flag: "AL" },
  { code: "am", label: "Amharic — አማርኛ", flag: "ET" },
  { code: "ar", label: "Arabic — العربية", flag: "SA" },
  { code: "hy", label: "Armenian — Հայերեն", flag: "AM" },
  { code: "az", label: "Azerbaijani — Azərbaycan", flag: "AZ" },
  { code: "eu", label: "Basque — Euskara", flag: "ES" },
  { code: "be", label: "Belarusian — Беларуская", flag: "BY" },
  { code: "bn", label: "Bengali — বাংলা", flag: "BD" },
  { code: "bs", label: "Bosnian — Bosanski", flag: "BA" },
  { code: "bg", label: "Bulgarian — Български", flag: "BG" },
  { code: "ca", label: "Catalan — Català", flag: "ES" },
  { code: "ceb", label: "Cebuano", flag: "PH" },
  { code: "zh", label: "Chinese (Simplified) — 中文", flag: "CN" },
  { code: "zh-TW", label: "Chinese (Traditional) — 繁體中文", flag: "TW" },
  { code: "co", label: "Corsican — Corsu", flag: "FR" },
  { code: "hr", label: "Croatian — Hrvatski", flag: "HR" },
  { code: "cs", label: "Czech — Čeština", flag: "CZ" },
  { code: "da", label: "Danish — Dansk", flag: "DK" },
  { code: "nl", label: "Dutch — Nederlands", flag: "NL" },
  { code: "en", label: "English", flag: "GB" },
  { code: "eo", label: "Esperanto" },
  { code: "et", label: "Estonian — Eesti", flag: "EE" },
  { code: "fi", label: "Finnish — Suomi", flag: "FI" },
  { code: "fr", label: "French — Français", flag: "FR" },
  { code: "fy", label: "Frisian — Frysk", flag: "NL" },
  { code: "gl", label: "Galician — Galego", flag: "ES" },
  { code: "ka", label: "Georgian — ქართული", flag: "GE" },
  { code: "de", label: "German — Deutsch", flag: "DE" },
  { code: "el", label: "Greek — Ελληνικά", flag: "GR" },
  { code: "gu", label: "Gujarati — ગુજરાતી", flag: "IN" },
  { code: "ht", label: "Haitian Creole", flag: "HT" },
  { code: "ha", label: "Hausa", flag: "NG" },
  { code: "haw", label: "Hawaiian — ʻŌlelo Hawaiʻi", flag: "US" },
  { code: "he", label: "Hebrew — עברית", flag: "IL" },
  { code: "hi", label: "Hindi — हिन्दी", flag: "IN" },
  { code: "hmn", label: "Hmong" },
  { code: "hu", label: "Hungarian — Magyar", flag: "HU" },
  { code: "is", label: "Icelandic — Íslenska", flag: "IS" },
  { code: "ig", label: "Igbo", flag: "NG" },
  { code: "id", label: "Indonesian — Bahasa Indonesia", flag: "ID" },
  { code: "ga", label: "Irish — Gaeilge", flag: "IE" },
  { code: "it", label: "Italian — Italiano", flag: "IT" },
  { code: "ja", label: "Japanese — 日本語", flag: "JP" },
  { code: "jv", label: "Javanese — Basa Jawa", flag: "ID" },
  { code: "kn", label: "Kannada — ಕನ್ನಡ", flag: "IN" },
  { code: "kk", label: "Kazakh — Қазақ", flag: "KZ" },
  { code: "km", label: "Khmer — ភាសាខ្មែរ", flag: "KH" },
  { code: "rw", label: "Kinyarwanda", flag: "RW" },
  { code: "ko", label: "Korean — 한국어", flag: "KR" },
  { code: "ku", label: "Kurdish — Kurdî" },
  { code: "ky", label: "Kyrgyz — Кыргызча", flag: "KG" },
  { code: "lo", label: "Lao — ລາວ", flag: "LA" },
  { code: "la", label: "Latin", flag: "VA" },
  { code: "lv", label: "Latvian — Latviešu", flag: "LV" },
  { code: "lt", label: "Lithuanian — Lietuvių", flag: "LT" },
  { code: "lb", label: "Luxembourgish — Lëtzebuergesch", flag: "LU" },
  { code: "mk", label: "Macedonian — Македонски", flag: "MK" },
  { code: "mg", label: "Malagasy", flag: "MG" },
  { code: "ms", label: "Malay — Bahasa Melayu", flag: "MY" },
  { code: "ml", label: "Malayalam — മലയാളം", flag: "IN" },
  { code: "mt", label: "Maltese — Malti", flag: "MT" },
  { code: "mi", label: "Maori — Te Reo Māori", flag: "NZ" },
  { code: "mr", label: "Marathi — मराठी", flag: "IN" },
  { code: "mn", label: "Mongolian — Монгол", flag: "MN" },
  { code: "my", label: "Myanmar (Burmese) — မြန်မာ", flag: "MM" },
  { code: "ne", label: "Nepali — नेपाली", flag: "NP" },
  { code: "no", label: "Norwegian — Norsk", flag: "NO" },
  { code: "ny", label: "Nyanja (Chichewa)", flag: "MW" },
  { code: "or", label: "Odia (Oriya) — ଓଡ଼ିଆ", flag: "IN" },
  { code: "ps", label: "Pashto — پښتو", flag: "AF" },
  { code: "fa", label: "Persian — فارسی", flag: "IR" },
  { code: "pl", label: "Polish — Polski", flag: "PL" },
  { code: "pt", label: "Portuguese — Português", flag: "PT" },
  { code: "pa", label: "Punjabi — ਪੰਜਾਬੀ", flag: "IN" },
  { code: "ro", label: "Romanian — Română", flag: "RO" },
  { code: "ru", label: "Russian — Русский", flag: "RU" },
  { code: "sm", label: "Samoan — Gagana Samoa", flag: "WS" },
  { code: "gd", label: "Scots Gaelic — Gàidhlig", flag: "GB" },
  { code: "sr", label: "Serbian — Српски", flag: "RS" },
  { code: "st", label: "Sesotho", flag: "LS" },
  { code: "sn", label: "Shona — ChiShona", flag: "ZW" },
  { code: "sd", label: "Sindhi — سنڌي", flag: "PK" },
  { code: "si", label: "Sinhala — සිංහල", flag: "LK" },
  { code: "sk", label: "Slovak — Slovenčina", flag: "SK" },
  { code: "sl", label: "Slovenian — Slovenščina", flag: "SI" },
  { code: "so", label: "Somali — Soomaali", flag: "SO" },
  { code: "es", label: "Spanish — Español", flag: "ES" },
  { code: "su", label: "Sundanese — Basa Sunda", flag: "ID" },
  { code: "sw", label: "Swahili — Kiswahili", flag: "TZ" },
  { code: "sv", label: "Swedish — Svenska", flag: "SE" },
  { code: "tl", label: "Tagalog (Filipino)", flag: "PH" },
  { code: "tg", label: "Tajik — Тоҷикӣ", flag: "TJ" },
  { code: "ta", label: "Tamil — தமிழ்", flag: "IN" },
  { code: "tt", label: "Tatar — Татарча", flag: "RU" },
  { code: "te", label: "Telugu — తెలుగు", flag: "IN" },
  { code: "th", label: "Thai — ภาษาไทย", flag: "TH" },
  { code: "tr", label: "Turkish — Türkçe", flag: "TR" },
  { code: "tk", label: "Turkmen — Türkmen", flag: "TM" },
  { code: "uk", label: "Ukrainian — Українська", flag: "UA" },
  { code: "ur", label: "Urdu — اردو", flag: "PK" },
  { code: "ug", label: "Uyghur — ئۇيغۇرچە" },
  { code: "uz", label: "Uzbek — O'zbek", flag: "UZ" },
  { code: "vi", label: "Vietnamese — Tiếng Việt", flag: "VN" },
  { code: "cy", label: "Welsh — Cymraeg", flag: "GB" },
  { code: "xh", label: "Xhosa — isiXhosa", flag: "ZA" },
  { code: "yi", label: "Yiddish — ייִדיש", flag: "IL" },
  { code: "yo", label: "Yoruba", flag: "NG" },
  { code: "zu", label: "Zulu — isiZulu", flag: "ZA" },
];
