type OpenMojiEntry = {
  code: string;
  label: string;
};

export const OPENMOJI_CATALOG: OpenMojiEntry[] = [
  { code: "1F60A", label: "smile" },
  { code: "1F604", label: "grin" },
  { code: "1F606", label: "laugh" },
  { code: "1F609", label: "wink" },
  { code: "1F60D", label: "love eyes" },
  { code: "1F618", label: "kiss" },
  { code: "1F917", label: "hug" },
  { code: "1F929", label: "star struck" },
  { code: "1F970", label: "hearts" },
  { code: "1F973", label: "party" },
  { code: "1F60E", label: "cool" },
  { code: "1F60F", label: "smirk" },
  { code: "1F913", label: "nerd" },
  { code: "1F920", label: "cowboy" },
  { code: "1F978", label: "disguise" },
  { code: "1F92A", label: "crazy" },
  { code: "1F92D", label: "oops" },
  { code: "1F92B", label: "shush" },
  { code: "1F914", label: "thinking" },
  { code: "1F9D0", label: "monocle" },
  { code: "1F60C", label: "relaxed" },
  { code: "1F634", label: "sleep" },
  { code: "1F924", label: "drool" },
  { code: "1F60B", label: "yum" },
  { code: "1F61C", label: "tongue" },
  { code: "1F911", label: "money" },
  { code: "1F4AA", label: "muscle" },
  { code: "1F47B", label: "ghost" },
  { code: "1F47D", label: "alien" },
  { code: "1F916", label: "robot" },
  { code: "1F47E", label: "monster" },
  { code: "1F479", label: "ogre" },
  { code: "1F47A", label: "goblin" },
  { code: "1F480", label: "skull" },
  { code: "1F383", label: "pumpkin" },
  { code: "1F984", label: "unicorn" },
  { code: "1F409", label: "dragon" },
  { code: "1F431", label: "cat" },
  { code: "1F436", label: "dog" },
  { code: "1F43B", label: "bear" },
  { code: "1F43C", label: "panda" },
  { code: "1F428", label: "koala" },
  { code: "1F981", label: "lion" },
  { code: "1F98A", label: "fox" },
  { code: "1F427", label: "penguin" },
  { code: "1F985", label: "eagle" },
  { code: "1F989", label: "owl" },
  { code: "1F99D", label: "raccoon" },
  { code: "1F43A", label: "wolf" },
  { code: "1F680", label: "rocket" },
  { code: "1F525", label: "fire" },
  { code: "2B50", label: "star" },
  { code: "1F31F", label: "glow" },
  { code: "1F308", label: "rainbow" },
  { code: "26A1", label: "lightning" },
  { code: "1F3AE", label: "gamepad" },
  { code: "1F3B8", label: "guitar" },
  { code: "1F3A7", label: "headphones" },
  { code: "1F4BB", label: "laptop" },
  { code: "2615", label: "coffee" },
  { code: "1F37B", label: "beer" },
];
